"""empty message

Revision ID: 186466117d4b
Revises: 977945ef71cf
Create Date: 2019-11-05 19:53:28.327745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186466117d4b'
down_revision = '977945ef71cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('file', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'file')
    # ### end Alembic commands ###
