"""empty message

Revision ID: b260dc5368d2
Revises: 4b9b51bdaca0
Create Date: 2019-11-07 09:54:25.291107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b260dc5368d2'
down_revision = '4b9b51bdaca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('file_type', sa.String(length=100), nullable=True))
    op.add_column('photo', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('photo', sa.Column('y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'y')
    op.drop_column('photo', 'x')
    op.drop_column('photo', 'file_type')
    # ### end Alembic commands ###
